POST http://localhost:5000/videos HTTP/1.1
content-type: application/json

{}

###

GET http://localhost:5000/videos HTTP/1.1

###

GET http://localhost:5000/videos/1 HTTP/1.1

###

DELETE http://localhost:5000/videos/1 HTTP/1.1