DROP TABLE IF EXISTS videos;
DROP TABLE IF EXISTS channels;

CREATE TABLE videos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NULL,
  date_created DATETIME NOT NULL
);

CREATE TABLE channels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  channel_name TEXT NULL
);