DROP TABLE IF EXISTS videos;
DROP TABLE IF EXISTS channels;

CREATE TABLE IF NOT EXISTS videos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NULL,
  published_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS channels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  channel_name TEXT NULL
);