DROP TABLE IF EXISTS Videos;
DROP TABLE IF EXISTS Channels;

CREATE TABLE IF NOT EXISTS Videos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NULL,
  published_at DATETIME NOT NULL
);

CREATE TABLE IF NOT EXISTS Channels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  channel_name TEXT NULL
);